name: Build Android Actions

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # Android arm64
          - os: android
            arch: aarch64
            runs: ubuntu-latest
            target: aarch64-linux-android
          # Android x86_64
          - os: android
            arch: x86_64
            runs: ubuntu-latest
            target: x86_64-linux-android
          # Android armv7
          - os: android
            arch: armv7
            runs: ubuntu-latest
            target: armv7-linux-androideabi
    runs-on: ${{ matrix.runs }}
    steps:
      - uses: actions/checkout@v6
      # 安装 Rust stable 版本
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      # 为 Android 添加 Java 编译器
      - name: Install Java toolchain
        if: ${{ matrix.os == 'android' }}
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      # 为 Android 添加 Android Studio 编译器
      - name: Install Android Studio
        uses: android-actions/setup-android@v4
        with:
          cmdline-tools-version: 9477386
      # 缓存 Rust Target 目录
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"
          key: ${{ matrix.os }}-${{ matrix.arch }}
      # 添加 Android/iOS toolchain
      - name: Install Rustup Android/iOS toolchain
        run: |
          rustup target add ${{ matrix.target }}
          cargo install cargo-mobile2
      # 开始生成图标
      - name: Generated icon
        run: |
          cargo install tauri-cli
          mkdir -p src-tauri
          echo -e '{"bundle":{"icon":["icons/32x32.png","icons/128x128.png","icons/128x128@2x.png","icons/icon.icns","icons/icon.ico"]}}' > src-tauri/tauri.conf.json
          cargo tauri icon ./app-icon.png
          rsync -av --remove-source-files src-tauri/icons/android/ gen/android/app/src/main/res/
          mkdir -p gen/android/app/src/main/assets
          rm -rf gen/android/app/src/main/res/**/*.webp
      # 开始调用 Java keytool 生成 Android 签名
      - name: Sign Android app
        run: |
          keytool -genkey -v -keystore ~/upload-keystore.jks -keyalg RSA -keysize 2048 --validity 10000 -alias upload -storepass ${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }} -dname "CN=xphost, OU=CandySharkStudio, O=CandySharkStudio, L=Beijing, ST=Beijing, C=CN"
          echo -e "storePassword=${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }}\nkeyPassword=${{ secrets.MY_ANDROID_KEYTOOL_PASSWORD }}\nkeyAlias=upload\nstoreFile=/home/runner/upload-keystore.jks" > gen/android/keystore.properties
      # 开始构建！
      - name: Start Build
        env:
          NDK_HOME: /usr/local/lib/android/sdk/ndk/29.0.14206865
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/29.0.14206865
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang
          CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER: /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang
          CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER: /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi28-clang
          CARGO_TARGET_I686_LINUX_ANDROID_LINKER: /usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android28-clang
        run: |
          cargo android apk build ${{ matrix.arch }} --release
      # 上传工件！
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Bundle-${{ matrix.os }}-${{ matrix.arch }}
          path: gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
          if-no-files-found: error
