name: Build Actions

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          # Windows x86_64
          - os: windows
            arch: x86_64
            runs: windows-latest
            target: x86_64-pc-windows-msvc
          # Windows arm64
          - os: windows
            arch: arm64
            runs: windows-11-arm
            target: aarch64-pc-windows-msvc
          # Windows i686
          - os: windows
            arch: i686
            runs: windows-latest
            target: i686-pc-windows-msvc
          # macOS arm64
          - os: macos
            arch: arm64
            runs: macos-latest
            target: aarch64-apple-darwin
          # macOS x86_64
          - os: macos
            arch: x86_64
            runs: macos-15-intel
            target: x86_64-apple-darwin
          # Linux x86_64
          - os: linux
            arch: x86_64
            runs: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # Linux arm64
          - os: linux
            arch: arm64
            runs: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.runs }}
    steps:
      - uses: actions/checkout@v6
      # 安装 Rust stable 版本
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      # 为 Linux 添加部分依赖
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev pkg-config
          sudo apt-get install -y xdg-utils
      # 开始打包正常的可执行文件
      - name: Build the app
        run: cargo build --release --target ${{ matrix.target }}
      - name: Bundle macOS App file
        if: ${{ matrix.os =='macos' }}
        run: |
          APP_DIR=target/${{ matrix.target }}/release/bundle/macos/ren-rs-refactor-desktop.app
          mkdir -p $APP_DIR/Contents/MacOS
          cp target/${{ matrix.target }}/release/ren-rs-refactor-desktop $APP_DIR/Contents/MacOS/ren-rs-refactor-desktop
          cat << EOF > $APP_DIR/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDevelopmentRegion</key>
              <string>en</string>
              <key>CFBundleExecutable</key>
              <string>ren-rs-refactor-desktop</string>
              <key>CFBundleIdentifier</key>
              <string>com.xphost.ren-rs-refactor-desktop</string>
              <key>CFBundleName</key>
              <string>ren-rs-refactor-desktop</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>CFBundleIconFile</key>
              <string>AppIcon</string>
              <key>HighResolutionCapable</key>
              <true/>
              <key>CFBundleInfoDictionaryVersion</key>
              <string>6.0</string>
          </dict>
          </plist>
          EOF
      - name: Upload the Linux app
        if: ${{ matrix.os == 'linux' }}
        uses: actions/upload-artifact@v7
        with:
          name: Bundle-${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/ren-rs-refactor-desktop
      - name: Upload the macOS app
        if: ${{ matrix.os == 'windows' }}
        uses: actions/upload-artifact@v7
        with:
          name: Bundle-${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/bundle/macos
      - name: Upload the Windows app
        if: ${{ matrix.os == 'windows' }}
        uses: actions/upload-artifact@v7
        with:
          name: Bundle-${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/ren-rs-refactor-desktop.exe