name: Build Actions

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          # Windows x86_64
          - os: windows
            arch: x86_64
            runs: windows-latest
            target: x86_64-pc-windows-msvc
          # Windows arm64
          - os: windows
            arch: arm64
            runs: windows-11-arm
            target: aarch64-pc-windows-msvc
          # Windows i686
          - os: windows
            arch: i686
            runs: windows-latest
            target: i686-pc-windows-msvc
          # macOS arm64
          - os: macos
            arch: arm64
            runs: macos-latest
            target: aarch64-apple-darwin
          # macOS x86_64
          - os: macos
            arch: x86_64
            runs: macos-15-intel
            target: x86_64-apple-darwin
          # Linux x86_64
          - os: linux
            arch: x86_64
            runs: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # Linux arm64
          - os: linux
            arch: arm64
            runs: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          # Android arm64
          - os: android
            arch: arm64
            runs: ubuntu-latest
            target: aarch64-linux-android
          # Android x86_64
          - os: android
            arch: x86_64
            runs: ubuntu-latest
            target: x86_64-linux-android
          # Android armv7
          - os: android
            arch: armv7
            runs: ubuntu-latest
            target: armv7-linux-androideabi
          # iOS arm64
          - os: ios
            arch: arm64
            runs: macos-latest
            target: aarch64-apple-ios

    runs-on: ${{ matrix.runs }}
    steps:
      - uses: actions/checkout@v6
      # 安装 Rust stable 版本
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      # 为 Android 添加 Java 编译器
      - name: Install Java toolchain
        if: ${{ matrix.os == 'android' }}
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
      # 为 Android 添加 Android Studio 编译器
      - name: Install Android NDK
        if: ${{ matrix.os == 'android' }}
        uses: android-actions/setup-android@v4
        with:
          cmdline-tools-version: 9477386
      # 为 Linux 添加部分依赖
      - name: Install Linux dependencies
        if: ${{ matrix.os == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev pkg-config
          sudo apt-get install -y xdg-utils
      # 添加 Android/iOS toolchain
      - name: Install Rustup Android toolchain
        if: ${{ matrix.os == 'android' || matrix.os == 'ios' }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo install cargo-mobile2
      # 开始打包正常的可执行文件
      - name: Build the app
        if: ${{ matrix.os != 'android' && matrix.os != 'ios' }}
        run: cargo build --release --target ${{ matrix.target }}
      # 开始打包 Android 并调用 Java keytool 生成签名
      - name: Build Android app and sign app
        if: ${{ matrix.platform == 'android' && matrix.platform != 'freebsd' }}
        env:
          NDK_HOME: /usr/local/lib/android/sdk/ndk/29.0.14206865
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/29.0.14206865
        run: |
